### PR TITLE
upgrade(moralis-angular-app): upgrade to angular 13.1.3 and moralis 1.1.0

### PR DESCRIPTION
**Pull request by attilacsanyi**

### CODE REVIEW

**Comment by Y0moo** [comment]
Nice work!

**Comment by attilacsanyi** [comment]
> Nice work!

Thank you @Y0moo :)

**Comment by playground** [comment]
I don't see this in the demo-apps, where can I try out moralis-angullar-app?

**Comment by attilacsanyi** [comment]
@playground I just realised Moralis Boilerplates repo has been cleaned up so not available there anymore.

So far there is not a fully fledged [angular-moralis](https://github.com/MoralisWeb3/angular-moralis) like [react-moralis](https://github.com/MoralisWeb3/react-moralis), but [here is my fork](https://github.com/attilacsanyi/demo-apps/tree/main/moralis-angular-app) which was the base for moralis-angular-app, where you can still see this upgrade.

I hope this helps.

**Comment by playground** [comment]
👍, will check it out.

**Pull request merged**
